import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProviderWrapper } from "@/features/auth/components/AuthProviderWrapper";

export const metadata: Metadata = {
  title: "Typeracer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <AuthProviderWrapper>
            {children}
            <Toaster />
          </AuthProviderWrapper>
        </main>
      </body>
    </html>
  );
}
