import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProviderWrapper } from "@/features/auth/components/AuthProviderWrapper";
import { SocketProvider } from "@/features/race/context/Socket";

export const metadata: Metadata = {
  title: "Typeracer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <AuthProviderWrapper>
            <SocketProvider>
              {children}
              <Toaster />
            </SocketProvider>
          </AuthProviderWrapper>
        </main>
      </body>
    </html>
  );
}
